-- Execute este SQL no Supabase > SQL Editor

create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  full_name text not null check (char_length(full_name) >= 3),
  phone text not null,
  email text not null,
  consent boolean not null default false,
  event_slug text not null default 'escola-mocos-profetas-07-08-11'
);

-- Evita inscrição duplicada por e-mail ou telefone no mesmo evento
create unique index if not exists registrations_event_email_unique
  on public.registrations (event_slug, lower(email));

create unique index if not exists registrations_event_phone_unique
  on public.registrations (event_slug, phone);

alter table public.registrations enable row level security;

-- Permite inscrições tanto para visitantes públicos (anon) quanto para usuários/administradores autenticados.
drop policy if exists "public can insert registrations" on public.registrations;
drop policy if exists "anyone can insert registrations" on public.registrations;
create policy "anyone can insert registrations"
on public.registrations
for insert
to anon, authenticated
with check (
  consent = true
  and char_length(full_name) >= 3
  and char_length(phone) >= 10
  and char_length(email) >= 5
);

-- Sequence oficial da coluna registration_number
-- create sequence if not exists public.registration_number_seq start 1;
-- alter table public.registrations add column if not exists registration_number bigint default nextval('public.registration_number_seq');

-- ==============================================================================
-- AUTOMAÇÃO DE CONTROLE DE SEQUÊNCIA (AFTER DELETE - STATEMENT LEVEL)
-- Reinicia a sequence para 1 apenas se a tabela ficar com 0 registros.
-- ==============================================================================

create or replace function public.reset_registration_number_seq_if_empty()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  -- 1. Verifica se ainda existe pelo menos um registro em public.registrations
  if exists (select 1 from public.registrations limit 1) then
    -- Se existir qualquer registro, NÃO faz nada na sequence
    return null;
  end if;

  -- 2. Se a tabela estiver completamente vazia (0 registros):
  perform setval(
    'public.registration_number_seq'::regclass,
    1,
    false
  );

  return null;
end;
$$;

drop trigger if exists trg_reset_registration_number_seq_if_empty on public.registrations;

create trigger trg_reset_registration_number_seq_if_empty
after delete on public.registrations
for each statement
execute function public.reset_registration_number_seq_if_empty();

-- Não crie policy de SELECT para anon.
-- Assim os visitantes não conseguem ler a lista de inscritos.
-- Para ver quantidade e dados, use o painel do Supabase autenticado.

-- Permite ao painel administrativo (usuários autenticados via Supabase Auth) ler os cadastros.
drop policy if exists "authenticated can select registrations" on public.registrations;
create policy "authenticated can select registrations"
on public.registrations
for select
to authenticated
using (true);

-- Consulta para contar inscritos no painel:
-- select count(*) as total_inscritos
-- from public.registrations
-- where event_slug = 'escola-mocos-profetas-07-08-11';

-- Consulta para exportar a lista:
-- select created_at, full_name, phone, email
-- from public.registrations
-- where event_slug = 'escola-mocos-profetas-07-08-11'
-- order by created_at desc;
